java/sigar: fix running with openjdk8
Running Cassandra 3 gave:
java.lang.UnsupportedClassVersionError: org/hyperic/sigar/SigarException has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 52.0

PR:	294323
Reported-by:	Lapo Luchini
Fixes:	f3a12dc72aa72af22212e3e37c5f29652eae0cbb "fix compilation with jdk21"
MFH:	2026Q2
Pointy-hat:	to me
(cherry picked from commit 39650b669d8253cfc1419e384741df7f5c7e2c4c)

NB: I included the portrevision bump of 86813e9ccf597695e26c8104e678f913689f1e93
although that commit is not merged. I think this makes it more clear that the
port in branch 2026Q2 is equal to the port in main now.