emulators/rpcs3: unbreak build after 1b59de75bd3d
In file included from rpcs3/Emu/Cell/lv2/sys_usbd.cpp:44:
rpcs3/Emu/../Emu/Io/LogitechG27.h:41:2: error: unknown type name 'SDL_HapticEffectID'; did you mean 'SDL_HapticEffect'?
   41 |         SDL_HapticEffectID effect_id = -1;
      |         ^~~~~~~~~~~~~~~~~~
      |         SDL_HapticEffect
/usr/local/include/SDL3/SDL_haptic.h:925:3: note: 'SDL_HapticEffect' declared here
  925 | } SDL_HapticEffect;
      |   ^
In file included from rpcs3/Emu/Cell/lv2/sys_usbd.cpp:44:
rpcs3/Emu/../Emu/Io/LogitechG27.h:41:33: error: no viable conversion from 'int' to 'SDL_HapticEffect'
   41 |         SDL_HapticEffectID effect_id = -1;
      |                                        ^~
/usr/local/include/SDL3/SDL_haptic.h:915:15: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'int' to 'const SDL_HapticEffect &' for 1st argument
  915 | typedef union SDL_HapticEffect
      |               ^~~~~~~~~~~~~~~~
/usr/local/include/SDL3/SDL_haptic.h:915:15: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'int' to 'SDL_HapticEffect &&' for 1st argument
  915 | typedef union SDL_HapticEffect
      |               ^~~~~~~~~~~~~~~~
In file included from rpcs3/Emu/Cell/lv2/sys_usbd.cpp:44:
rpcs3/Emu/../Emu/Io/LogitechG27.h:143:55: error: default member initializer for 'effect_id' needed within definition of enclosing class 'logitech_g27_ffb_slot' outside of member functions
  143 |         std::array<logitech_g27_ffb_slot, 4> m_effect_slots {};
      |                                                              ^
rpcs3/Emu/../Emu/Io/LogitechG27.h:41:21: note: default member initializer declared here
   41 |         SDL_HapticEffectID effect_id = -1;
      |                            ^
3 errors generated.

Reported by:	pkg-fallout

(direct commit to 2026Q2 as d21a34fe406a is missing on the branch)