security/libssh: Mark BROKEN on 15+ and add backup for MASTER_SITES
Fails to build on 15+,
src/mlkem_crypto.c:31:10: fatal error: 'openssl/ml_kem.h' file not found

Add temporary backup for MASTER_SITES to avoid build failures on other
versions and of consumers as main upstream site current truncates
downloads

Thanks to eduardo@ for verifying build issues on -CURRENT

PR:		294268
Approved by:	blanket, just fix it

(cherry picked from commit 4211f99a216d4f440b3b804a1e6db475087e3ed2)