net-mgmt/arts++: broken, deprecate
 - unmaintained
 - deprecated by upstream
 - broken due to C++ changes:

/usr/include/c++/v1/__type_traits/is_trivially_relocatable.h:37:83: error: '__trivially_relocatable' is a private member of 'std::pair<unsigned int, unsigned int>'
   37 |                                          __enable_if_t<is_same<_Tp, typename _Tp::__trivially_relocatable>::value> >
      |                                                                                   ^
/usr/include/c++/v1/__memory/uninitialized_algorithms.h:626:44: note: during template argument deduction for class template partial specialization '__libcpp_is_trivially_relocatable<_Tp, __enable_if_t<is_same<_Tp, typename _Tp::__trivially_relocatable>::value> >' [with _Tp = ArtsSelection<unsigned int>]
  626 |   if (__libcpp_is_constant_evaluated() || !__libcpp_is_trivially_relocatable<_Tp>::value ||
      |                                            ^
/usr/include/c++/v1/__memory/uninitialized_algorithms.h:626:44: note: in instantiation of template class 'std::__libcpp_is_trivially_relocatable<ArtsSelection<unsigned int> >' requested here
/usr/include/c++/v1/vector:1052:8: note: in instantiation of function template specialization 'std::__uninitialized_allocator_relocate<std::allocator<ArtsSelection<unsigned int> >, ArtsSelection<unsigned int> >' requested here
 1052 |   std::__uninitialized_allocator_relocate(
      |        ^
/usr/include/c++/v1/vector:1502:3: note: in instantiation of member function 'std::vector<ArtsSelection<unsigned int> >::__swap_out_circular_buffer' requested here
 1502 |   __swap_out_circular_buffer(__v);
      |   ^
/usr/include/c++/v1/vector:1526:13: note: in instantiation of function template specialization 'std::vector<ArtsSelection<unsigned int> >::__push_back_slow_path<ArtsSelection<unsigned int> >' requested here
 1526 |     __end = __push_back_slow_path(std::move(__x));
      |             ^
../include/ArtsSelectionSet.hh:73:11: note: in instantiation of member function 'std::vector<ArtsSelection<unsigned int> >::push_back' requested here
   73 |     this->push_back(ArtsSelection<Type>(value));
      |           ^
ArtsObjectTypeSelectionSet.lex:107:15: note: in instantiation of member function 'ArtsSelectionSet<unsigned int>::Add' requested here
  107 |         this->Add(test);
      |               ^
1 error generated.

MFH:		2026Q2
(cherry picked from commit 5ff0a60ac672740595722ae6658b0e5a22faf4fb)